// Writes the "What do you want to do?" section of README.md: for each need
// in scripts/lib/data.js, every listed system that meets it, with what it
// does and what it leaves you to rule on, copied from its own table row.
// The section lives between two markers and is rebuilt on every run, so it
// cannot fall out of step with the tables. Run everything with:
//   node scripts/build.js
const fs = require('fs');
const path = require('path');
const { ROOT, readme, readRows, words } = require('../lib/readme');
const { NEEDS, TAGS, CATS, CHOOSER_URL } = require('../lib/data');

const START = '<!-- needs:start -->';
const END = '<!-- needs:end -->';
const NOTE = '<!-- Generated by node scripts/build.js from the category tables below and scripts/lib/data.js. Edit those, not this section. -->';

// ---- agree with the README tables before writing anything ----
const rows = readRows();
const errors = [];
for (const r of rows) {
  if (!TAGS[r.name] || !TAGS[r.name].length) errors.push('README lists "' + r.name + '" but scripts/lib/data.js puts it under no need. Add it to TAGS.');
}
for (const [name, needs] of Object.entries(TAGS)) {
  if (!rows.some((r) => r.name === name)) errors.push('scripts/lib/data.js has "' + name + '" but the README tables do not. Remove it from TAGS.');
  for (const n of needs) if (!NEEDS[n]) errors.push('"' + name + '" is put under "' + n + '", which is not a need in NEEDS.');
}
for (const key of Object.keys(NEEDS)) {
  if (!rows.some((r) => (TAGS[r.name] || []).includes(key))) errors.push('No listed system meets the need "' + key + '". Give it a system or remove it.');
}
if (errors.length) {
  console.error('Refusing to write the README needs section:\n  ' + errors.join('\n  '));
  process.exit(1);
}

// ---- build the section ----
const cap = (s) => s[0].toUpperCase() + s.slice(1);
const anchor = (cat) => '#' + cat.toLowerCase().replace(/\s+/g, '-');
const out = [START, NOTE];
for (const [key, need] of Object.entries(NEEDS)) {
  const members = rows
    .filter((r) => TAGS[r.name].includes(key))
    .sort((a, b) => CATS[a.cat].rank - CATS[b.cat].rank || rows.indexOf(a) - rows.indexOf(b));
  const cats = [...new Set(members.map((m) => m.cat))];
  const n = members.length;
  let lead;
  if (cats.length > 1) lead = cap(words(n)) + ' systems across ' + words(cats.length) + ' categories, so they leave you different things to rule on.';
  else if (n === 1) lead = 'One system, in ' + cats[0] + '.';
  else if (n === 2) lead = 'Both in ' + cats[0] + ', so they leave you the same kind of thing to rule on.';
  else lead = cap(words(n)) + ' systems, all in ' + cats[0] + ', so they leave you the same kind of thing to rule on.';
  // A collapsed panel per need: the reader clicks the need and its systems
  // open. GitHub renders details/summary natively, with no script. The blank
  // line after the summary is what lets the markdown table inside render.
  out.push('', '<details>', '<summary><b>' + need.label + '</b> &middot; ' + n + (n === 1 ? ' system' : ' systems') + '</summary>', '');
  out.push(lead + ' [Compare them side by side](' + CHOOSER_URL + '#job=' + key + ').', '');
  out.push('| System | What it does | What you still rule on | Category |', '| --- | --- | --- | --- |');
  for (const m of members) {
    out.push('| [' + m.name + '](' + m.url + ') | ' + m.cells[1] + ' | ' + m.cells[2] + ' | [' + m.cat + '](' + anchor(m.cat) + ') |');
  }
  out.push('', '</details>');
}
out.push('', END);
const block = out.join('\n');

// ---- put it between the markers ----
const text = readme();
const i = text.indexOf(START), j = text.indexOf(END);
if (i < 0 || j < 0 || j < i) {
  console.error('README.md needs the markers ' + START + ' and ' + END + ' around the needs section.');
  process.exit(1);
}
const next = text.slice(0, i) + block + text.slice(j + END.length);

// ---- the one count the README prose states about the list as a whole ----
const want = cap(words(rows.length)) + ' systems a researcher can use today';
if (!next.includes(want)) {
  console.error('README is out of step with its tables. Expected to find: "' + want + '"');
  process.exit(1);
}

if (next !== text) fs.writeFileSync(path.join(ROOT, 'README.md'), next);
const per = Object.keys(NEEDS).map((k) => k + ' ' + rows.filter((r) => TAGS[r.name].includes(k)).length).join(', ');
console.log('readme: needs section ' + (next !== text ? 'rewritten' : 'unchanged') + ' (' + per + ')');
